### ISSUE TITLE
US1 - Fixed Game Demo

### ISSUE THREAD

**Issue by ChristophLeuker** [ChristophLeuker/journal-app#6]
## Value Proposition

**As a** user
**I want to** see a scoreboard  
**so that** i can see how i can write my match
​

## Description

![Image](https://user-images.githubusercontent.com/131157050/247903521-d79a8c98-8062-487a-8041-913fb40c7cbf.png)

​

## Acceptance Criteria

- [ ] see a fixed match of 501 D.O.
- [ ] a header with the game type is visible
      ​

## Tasks

- [ ] create branch 501Game
- [ ] create Page/501Game
- [ ] create a header with the game type
- [ ] add a tabel with 4 columns and 11 rows
- [ ] add two text fields for who is playing
- [ ] add fixed input
      ​

**Comment by julialoeschel** [comment]
Hey! great first Story. 
I would like to know if it can scoll at an point or fits the screen?
and I read that you are hardcoding the scores - wich is absolutely fine. 
**if** you planning on creating dummy data here - this should be a task. 

just tow minor tougths on this - other than that, super nice!!
