### ISSUE TITLE
US3 - Setup Game Page

### ISSUE THREAD

**Issue by ChristophLeuker** [ChristophLeuker/journal-app#8]
## Value Proposition

**As a** user
**I want to** setup a game with the names of the players
**so that** i know who is playing the game
​

## Description

![Image](https://user-images.githubusercontent.com/131157050/247945929-aba495f0-b622-4846-a088-49fb6a63988a.png)

​

## Acceptance Criteria

- [ ] see a page with two input-fields to tell the name of the players
- [ ] have a button to finally create a game
- [ ] a header with page description is visible

      ​

## Tasks

- [ ] create branch creategamepage
- [ ] create a createGame component
- [ ] add a heading
- [ ] add a form with 2 input fields and labels
- [ ] add a create game button which link to the 501 game
- [ ] styling with style components

**Comment by ryliecc** [comment]
everything included, well expressed and easy to understand :) well done!
